server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: scholarship
      username: scholarship
      password: scholarship
      authentication-database: admin

management:
  health:
    redis:
      enabled: false

jwt:
  secret-key: secret
  ttl: 86400000
auth:
  nonAuthPaths:
    - path: /api/v1/auth/login
      method: POST
    - path: /api/v1/auth
      method: POST